name: peemoti
description: "My portfolio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.4.3
  webview_flutter_web: ^0.2.2+4
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.2
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Rubik Glitch
      fonts:
        - asset: fonts/RubikGlitch-Regular.ttf
    - family: Dancing Script
      fonts:
        - asset: fonts/DancingScript-VariableFont_wght.ttf
    - family: Kanit
      fonts:
        - asset: fonts/kanit/Kanit-Regular.ttf
        - asset: fonts/kanit/Kanit-Italic.ttf
          style: italic
        - asset: fonts/kanit/Kanit-Thin.ttf
          weight: 100
        - asset: fonts/kanit/Kanit-ExtraLight.ttf
          weight: 200
        - asset: fonts/kanit/Kanit-Light.ttf
          weight: 300
        - asset: fonts/kanit/Kanit-Regular.ttf
          weight: 400
        - asset: fonts/kanit/Kanit-Medium.ttf
          weight: 500
        - asset: fonts/kanit/Kanit-SemiBold.ttf
          weight: 600
        - asset: fonts/kanit/Kanit-Bold.ttf
          weight: 700
        - asset: fonts/kanit/Kanit-ExtraBold.ttf
          weight: 800
        - asset: fonts/kanit/Kanit-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
